name: Steph and Tim get Married
url: http://stephandtimgetmarried.com

timezone: America/Toronto
exclude: ["Gemfile", "Gemfile.lock"]

future: true
permalink: /:title
relative_permalinks: false

markdown: redcarpet
 
sass:
    sass_dir: _sass
    style: :compressed

redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - fenced_code_blocks
    - disable_indented_code_blocks
    - autolink
    - strikethrough
    - lax_spacing
    - superscript
    - with_toc_data
